name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  quality-check:
    name: quality check (CI)
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install HTMLHint
        run: npm install -g htmlhint

      - name: run HTMLHint
        run: htmlhint "**/*.html"

      - name: link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: ". --verbose"

  docker-build:
    name: build & push docker
    needs: quality-check
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: push docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    name: deploy GitHub pages
    needs: docker-build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup pages
        uses: actions/configure-pages@v4

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4