name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  quality-check:
    name: Quality Check (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run HTMLHint
        run: htmlhint "**/*.html"

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: ". --verbose"